baseURL = 'https://josephpinder.com/'
languageCode = 'en-us'
title = 'Joseph Pinder'

upload_dir = "static/uploads"
public_path = "/uploads"
disableKinds = [ "taxonomy", "term" ]

uglyURLs = true

[pagination]
  pagerSize = 6

[ params ]
  version = "1738220434631"
  twic = "jsphpndr"
  share = "/uploads/joseph-pinder-share.jpg"
  logo = "/uploads/joseph-pinder-logo.png"
  # Facebook App ID
  app_id = "223848628924279"
  error = true

[menus]
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true

    # Links
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        enableDefault = true        

enableGitInfo = true
