name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
    
permissions:
  contents: write  # 👈 Grants permission to push changes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ✅ Step 2: Set Up Hugo
      - name: Set Up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.142.0'
          extended: true  # Ensure extended version is used

      # ✅ Step 3: Clear Hugo Cache (optional but recommended)
      - name: Clear Hugo Cache
        run: hugo mod clean

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      # ✅ Step 4: Build the Hugo Site
      - name: Build with Hugo
        run: hugo --minify --enableGitInfo

      # ✅ Step 5: Debug - List Generated Files
      - name: List Public Directory
        run: ls -R public/  # Helps verify RSS file generation

      # ✅ Step 6: Run Update Script
      - name: Run Update Script
        run: bash update-readme.sh

      - name: Commit Changes
        run: |
          git diff
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Automated update of README 🚀" || echo "No changes to commit"
          git push
