name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.142.0'

      - name: Run Update Script
        run: bash update-readme.sh

      - name: Commit Changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Automated update of README 🚀" || echo "No changes to commit"
          git push
